### ISSUE TITLE
Plans to release on pypi?

### ISSUE THREAD

**Issue by matentzn** [KRR-Oxford/OWL2Vec-Star#1]
Hey @ChenJiaoyan @ernestojimenezruiz 

are there any plans to release owl2vec* on pypi?
If not would you be able to provide a more modular design of the code, with a requirements.txt and setup script? That would really help with reproducibility etc.

Thanks! Cool paper by the way (just read the SiamNN+owl2vec* one).

**Comment by ChenJiaoyan** [comment]
Hi Nico, Thanks a lot for your suggestions. They are very helpful. We try to update the codes here and there when we have some free time. I would spend some time on April to update it.

**Comment by ernestojimenezruiz** [comment]
Hi Nico
We have released owl2vec* on pypi thanks to Vincenzo Cutrona.
Please give it a look.

**Comment by matentzn** [comment]
Awesome, will down asap! Super cool.
